// Flat key → [English, Dutch]. Values are strings or string lists (for prose blocks).
export type Entry = [string, string] | [string[], string[]];

export const DICT: Record<string, Entry> = {
  // ---------- nav / footer ----------
  "nav.jobs": ["Browse Jobs", "Vacatures"],
  "nav.how": ["How It Works", "Hoe het werkt"],
  "nav.guide": ["Knowledge base", "Kennisbank"],
  "nav.employers": ["For employers", "Werkgevers"],
  "nav.about": ["About", "Over ons"],
  "nav.contact": ["Contact", "Contact"],
  "nav.login": ["Log in", "Inloggen"],
  "nav.register": ["Get started", "Aan de slag"],
  "nav.logout": ["Log out", "Uitloggen"],
  "nav.dashboard": ["Dashboard", "Dashboard"],
  "nav.langLabel": ["Language", "Taal"],
  // Shown in the language being offered (components/LanguageHint.tsx).
  "langHint.text": ["This page is also available in English.", "Deze pagina is ook in het Nederlands beschikbaar."],
  "langHint.switch": ["Switch to English", "Naar het Nederlands"],
  "langHint.stay": ["Stay in Dutch", "Blijf in het Engels"],
  "footer.tagline": [
    "The job board for international students in the Netherlands. Every vacancy states its English requirement and work-permit support up front — no guessing, no dead ends.",
    "De vacaturebank voor internationale studenten in Nederland. Bij elke vacature staat vooraf welke Engelse taalvaardigheid nodig is en of er hulp is met een werkvergunning — geen gokwerk, geen doodlopende wegen.",
  ],
  "footer.students": ["Students", "Studenten"],
  "footer.company": ["Company", "Bedrijf"],
  "footer.browse": ["Browse jobs", "Vacatures bekijken"],
  "footer.permits": ["Working as a student in NL", "Werken als student in NL"],
  "footer.how": ["How it works", "Hoe het werkt"],
  "footer.createAccount": ["Create an account", "Account aanmaken"],
  "footer.about": ["About us", "Over ons"],
  "footer.employers": ["For employers", "Voor werkgevers"],
  "footer.privacy": ["Privacy policy", "Privacybeleid"],
  "footer.terms": ["Terms of service", "Algemene voorwaarden"],
  "footer.legal": [
    "The Netherlands. Not affiliated with IND or UWV.",
    "Nederland. Niet verbonden aan de IND of het UWV.",
  ],

  // ---------- shared labels ----------
  "label.english_only": ["English only", "Alleen Engels"],
  "label.basic_dutch": ["Basic Dutch welcome", "Basis Nederlands welkom"],
  "label.dutch_required": ["Dutch required", "Nederlands vereist"],
  "label.part_time": ["Part-time job", "Bijbaan"],
  "label.internship": ["Internship / Stage", "Stage"],
  "label.working_student": ["Working student", "Werkstudent"],
  "label.graduate": ["Graduate / starter", "Starter"],
  // What the employer states it will do — never a promise that a permit is granted.
  "label.twv_provided": ["Employer applies for a TWV", "Werkgever vraagt TWV aan"],
  "label.eu_eea": ["EU/EEA/Swiss nationals (no TWV)", "EU/EER/Zwitserse nationaliteit (geen TWV)"],
  "label.freelance_kvk": ["Freelance (KvK registration)", "Freelance (KvK-inschrijving)"],
  "label.none": ["No TWV application", "Geen TWV-aanvraag"],
  "label.on_site": ["On-site", "Op locatie"],
  "label.hybrid": ["Hybrid", "Hybride"],
  "label.remote": ["Remote", "Op afstand"],
  "label.applied": ["Applied", "Gesolliciteerd"],
  "label.under_review": ["Under review", "In behandeling"],
  "label.interview": ["Interview", "Gesprek"],
  "label.accepted": ["Accepted", "Aangenomen"],
  "label.rejected": ["Not selected", "Afgewezen"],
  "label.contract_employment": ["Employment contract", "Arbeidsovereenkomst (loondienst)"],
  "label.contract_on_call": ["On-call contract", "Oproepcontract"],
  "label.contract_agency": ["Via an employment agency", "Via een uitzendbureau"],
  "label.contract_internship": ["Internship agreement", "Stageovereenkomst"],
  "label.contract_freelance": ["Freelance (self-employed)", "Zelfstandig (freelance)"],
  "label.schedule_evening": ["Evening work", "Avondwerk"],
  "label.schedule_weekend": ["Weekend work", "Weekendwerk"],
  "label.schedule_holiday": ["Holiday work", "Vakantiewerk"],
  "job.perHour": ["/hour", "/uur"],
  "job.perMonth": ["/month", "/maand"],
  "job.payNotStated": ["Pay not stated", "Salaris niet opgegeven"],
  "job.closed": ["Closed", "Gesloten"],
  "job.perWeek": ["h / week", "uur / week"],
  "job.view": ["View & apply →", "Bekijk & solliciteer →"],
  "job.appliedShort": ["Applied ✓", "Gesolliciteerd ✓"],
  "job.save": ["Save job", "Vacature opslaan"],
  "job.saved": ["Saved", "Opgeslagen"],
  "job.freshSponsored": ["Fresh Vacancy. Sponsored", "Fresh Vacancy. Gesponsord"],
  "job.featuredOrganic": ["Featured. Not sponsored", "Uitgelicht. Niet gesponsord"],
  "toast.saved": ["Job saved", "Vacature opgeslagen"],
  "toast.unsaved": ["Removed from saved jobs", "Verwijderd uit opgeslagen vacatures"],
  "toast.saveLogin": ["Log in as a student to save jobs", "Log in als student om vacatures op te slaan"],
  "toast.saveStudentOnly": ["Only student accounts can save jobs", "Alleen studentaccounts kunnen vacatures opslaan"],
  "toast.saveFailed": ["Could not update saved jobs", "Kon opgeslagen vacatures niet bijwerken"],
  "common.cancel": ["Cancel", "Annuleren"],
  "common.saving": ["Saving…", "Opslaan…"],
  "verify.banner": [
    "Verify your email before applying or publishing a vacancy.",
    "Bevestig je e-mailadres voordat je solliciteert of een vacature publiceert.",
  ],
  "verify.resend": ["Resend verification email", "Verificatiemail opnieuw sturen"],
  "verify.sent": ["Verification email sent", "Verificatiemail verstuurd"],
  "verify.failed": ["Could not send the email", "Kon de e-mail niet versturen"],
  "account.deleteTitle": ["Delete account", "Account verwijderen"],
  "account.deleteBody": [
    "Permanently delete your account and the data attached to it. This cannot be undone.",
    "Verwijder je account en de gekoppelde gegevens definitief. Dit kan niet ongedaan worden gemaakt.",
  ],
  "account.deleteConfirm": [
    "Permanently delete your DutchVacancy account?",
    "Je DutchVacancy-account definitief verwijderen?",
  ],
  "account.deleteButton": ["Delete my account", "Mijn account verwijderen"],
  "account.deleted": ["Your account has been deleted", "Je account is verwijderd"],
  "account.deleteFailed": ["Could not delete your account", "Kon je account niet verwijderen"],

  // ---------- home ----------
  "home.badge": ["For international students in NL", "Voor internationale studenten in NL"],
  "home.h1a": ["Dutch jobs that", "Nederlandse banen die"],
  "home.h1b": ["hire in English.", "in het Engels werken."],
  "home.lead": [
    "Stop guessing whether a vacancy needs fluent Dutch. Every vacancy on DutchVacancy states its language requirement up front, plus the hours, pay and contract type whenever the employer provides them.",
    "Geen gokwerk meer of een vacature vloeiend Nederlands vereist. Bij elke vacature op DutchVacancy staat vooraf de taaleis, plus de uren, het loon en de contractvorm zodra de werkgever die opgeeft.",
  ],
  "home.searchPlaceholder": ["Job title, skill or company", "Functietitel, vaardigheid of bedrijf"],
  "home.allCities": ["All cities", "Alle steden"],
  "home.search": ["Search", "Zoeken"],
  "home.studentCta": ["Create a student account", "Maak een studentaccount"],
  "home.employerCta": ["I'm hiring students", "Ik zoek studenten"],
  "home.searchWhat": ["What are you looking for?", "Wat zoek je?"],
  "home.searchWhere": ["Where?", "Waar?"],
  "home.englishOnly": ["Only vacancies where English is enough", "Alleen vacatures waarvoor Engels genoeg is"],
  // Each line matches a field every published vacancy has (or states when missing).
  "home.factsTitle": ["On every vacancy", "Dit staat bij elke vacature"],
  "home.fact1": [
    "The language requirement: English only, basic Dutch welcome, or Dutch required",
    "De taaleis: alleen Engels, basis Nederlands welkom, of Nederlands vereist",
  ],
  "home.fact2": [
    "The closing date, so you never apply to a closed vacancy",
    "De sluitingsdatum, zodat je nooit op een gesloten vacature reageert",
  ],
  "home.fact3": [
    "Hours, schedule and pay per hour or per month, when the employer states them",
    "Uren, rooster en loon per uur of per maand, als de werkgever ze opgeeft",
  ],
  "home.fact4": [
    "Whether the employer applies for a work permit (TWV)",
    "Of de werkgever een werkvergunning (TWV) aanvraagt",
  ],
  "home.factsLink": [
    "What are you allowed to do as an international student? Read the knowledge base",
    "Wat mag je als internationale student? Lees de kennisbank",
  ],
  "home.statJobs": ["Live student vacancies", "Actuele studentenvacatures"],
  "home.statEmployers": ["Employers with open vacancies", "Werkgevers met open vacatures"],
  "home.statEnglish": ["No Dutch required", "Geen Nederlands vereist"],
  "home.statRate": ["Average hourly rate", "Gemiddeld uurloon"],
  "home.featuredTitle": ["Fresh English vacancies", "Nieuwe Engelstalige vacatures"],
  "home.featuredLead": [
    "Roles across the Netherlands with clear language, hours and permit information.",
    "Functies door heel Nederland met duidelijke informatie over taal, uren en vergunningen.",
  ],
  "home.cardEnglish": ["English requirements up front", "Engelse taaleis direct duidelijk"],
  "home.cardEnglishBody": ["Know the working language before you apply", "Ken de werktaal voordat je solliciteert"],
  "home.cardClear": ["Clear employment details", "Duidelijke arbeidsvoorwaarden"],
  "home.cardClearBody": ["Hours, pay and contract type when stated", "Uren, loon en contractvorm als ze zijn opgegeven"],
  "home.viewAll": ["View all jobs", "Alle vacatures bekijken"],
  "home.featuredEmpty": [
    "No vacancies online yet. New vacancies appear here as soon as employers publish them.",
    "Nog geen vacatures online. Nieuwe vacatures verschijnen hier zodra werkgevers ze plaatsen.",
  ],
  "home.featuredOffline": [
    "Vacancies load as soon as the job service is reachable. Meanwhile, browse the guide below.",
    "Vacatures worden geladen zodra de vacatureservice bereikbaar is. Bekijk intussen de gids hieronder.",
  ],
  "home.pathsTitle": ["Two paths, one platform", "Twee routes, één platform"],
  "home.pathsLead": [
    "Whether you're looking for your first Dutch payslip or your next international hire.",
    "Of je je eerste Nederlandse loonstrook zoekt of je volgende internationale medewerker.",
  ],
  "home.tabStudents": ["For students", "Voor studenten"],
  "home.tabEmployers": ["For employers", "Voor werkgevers"],
  "home.step": ["Step", "Stap"],
  "home.student1t": ["Search without the language wall", "Zoeken zonder taalbarrière"],
  "home.student1b": [
    "Every vacancy states its English requirement, so you only see roles you can actually get.",
    "Bij elke vacature staat de Engelse taaleis, dus je ziet alleen functies die je echt kunt krijgen.",
  ],
  "home.student2t": ["Build one student profile", "Maak één studentprofiel"],
  "home.student2b": [
    "University, study programme, CV link and availability — reused on every application.",
    "Universiteit, studie, cv-link en beschikbaarheid — hergebruikt bij elke sollicitatie.",
  ],
  "home.student3t": ["Track every application", "Volg elke sollicitatie"],
  "home.student3b": [
    "Applied, under review, interview or offer: follow each status from your dashboard.",
    "Gesolliciteerd, in behandeling, gesprek of aanbod: volg elke status in je dashboard.",
  ],
  "home.employer1t": ["Publish a vacancy in minutes", "Plaats een vacature in enkele minuten"],
  "home.employer1b": [
    "State the English level, hours and permit support — students self-select correctly.",
    "Vermeld het Engelse niveau, de uren en de vergunningshulp — studenten selecteren zichzelf goed.",
  ],
  "home.employer2t": ["Review real applicants", "Beoordeel echte kandidaten"],
  "home.employer2b": [
    "Motivation letter, university and CV link for every candidate in one pipeline.",
    "Motivatie, universiteit en cv-link van elke kandidaat in één overzicht.",
  ],
  "home.employer3t": ["Hire international talent", "Neem internationaal talent aan"],
  "home.employer3b": [
    "Reach international students and English-speaking candidates across the Netherlands.",
    "Bereik internationale studenten en Engelstalige kandidaten in heel Nederland.",
  ],
  "home.citiesTitle": ["Explore the student hubs", "Ontdek de studentensteden"],
  "home.citiesRoles": ["+ roles", "+ functies"],
  // The rules themselves live in the knowledge base (backend/content/kb), where
  // every claim has a checked official source — not in these UI strings.
  "home.legalTitle": [
    "Working in the Netherlands as an international student",
    "Werken als internationale student in Nederland",
  ],
  "home.legalLead": [
    "Permits, insurance, contracts and pay, explained in plain language. Every article names its official sources.",
    "Vergunningen, verzekering, contracten en loon, in duidelijke taal uitgelegd. Elk artikel noemt zijn officiële bronnen.",
  ],
  "home.legalCta": ["Open the knowledge base", "Naar de kennisbank"],
  "home.ctaTitle": ["Ready to launch your Dutch career?", "Klaar om je Nederlandse carrière te starten?"],
  "home.ctaLead": [
    "Create a free account and apply to your first English-speaking vacancy today.",
    "Maak een gratis account en solliciteer vandaag op je eerste Engelstalige vacature.",
  ],
  "home.ctaFind": ["Find your job", "Vind je baan"],
  "home.ctaPost": ["Post a vacancy", "Plaats een vacature"],

  // ---------- jobs ----------
  "jobs.title": ["English-speaking student jobs", "Engelstalige studentenbanen"],
  "jobs.lead": [
    "Filter by city, English requirement and work-permit support.",
    "Filter op stad, Engelse taaleis en hulp bij werkvergunningen.",
  ],
  "jobs.searchPlaceholder": [
    "Search job title, company or keyword",
    "Zoek op functietitel, bedrijf of trefwoord",
  ],
  "jobs.filters": ["Filters", "Filters"],
  "jobs.clearAll": ["Clear all", "Alles wissen"],
  "jobs.filterCity": ["City", "Stad"],
  "jobs.filterEnglish": ["English requirement", "Engelse taaleis"],
  "jobs.filterType": ["Job type", "Soort baan"],
  "jobs.filterPermit": ["Work permit (TWV)", "Werkvergunning (TWV)"],
  "jobs.filterWork": ["Work arrangement", "Werkvorm"],
  "jobs.filterRate": ["Hourly rate", "Uurloon"],
  "jobs.rate15": ["€ 15+ / hour", "€ 15+ / uur"],
  "jobs.rate18": ["€ 18+ / hour", "€ 18+ / uur"],
  "jobs.rate22": ["€ 22+ / hour", "€ 22+ / uur"],
  "jobs.loading": ["Loading vacancies…", "Vacatures laden…"],
  "jobs.offline": ["Job data is temporarily unavailable.", "Vacaturegegevens zijn tijdelijk niet beschikbaar."],
  "jobs.found": ["vacancies found", "vacatures gevonden"],
  "jobs.foundOne": ["vacancy found", "vacature gevonden"],
  "jobs.emptyTitle": ["No vacancies match these filters", "Geen vacatures met deze filters"],
  "jobs.emptyBody": [
    "Try clearing a filter or widening your city selection.",
    "Wis een filter of kies meer steden.",
  ],

  // ---------- job detail ----------
  "detail.back": ["All vacancies", "Alle vacatures"],
  "detail.unavailableTitle": ["Vacancy unavailable", "Vacature niet beschikbaar"],
  "detail.unavailableBody": [
    "This vacancy may have been closed or the job service is unreachable right now.",
    "Deze vacature is mogelijk gesloten of de vacatureservice is nu niet bereikbaar.",
  ],
  "detail.backToJobs": ["Back to all jobs", "Terug naar alle vacatures"],
  "detail.about": ["About this role", "Over deze functie"],
  "detail.requirements": ["What you bring", "Wat je meebrengt"],
  "detail.perks": ["What you get", "Wat je krijgt"],
  "detail.aboutCompany": ["About", "Over"],
  "detail.industry": ["Industry", "Branche"],
  "detail.base": ["Base", "Vestiging"],
  "detail.website": ["Website", "Website"],
  "detail.visit": ["Visit", "Bezoeken"],
  "detail.gross": ["gross per hour", "bruto per uur"],
  "detail.hoursWeek": ["hours per week", "uur per week"],
  "detail.applicants": ["applicants", "kandidaten"],
  "detail.applicant": ["applicant", "kandidaat"],
  "detail.alreadyApplied": ["You already applied to this role", "Je hebt al op deze functie gesolliciteerd"],
  "detail.applyNow": ["Apply now", "Solliciteer nu"],
  "detail.guideTitle": ["Good to know", "Goed om te weten"],
  "detail.guideEmpty": [
    "Whether you may take this job depends on your nationality and residence permit. The official bodies decide; our knowledge base lists them.",
    "Of je deze baan mag doen, hangt af van je nationaliteit en verblijfsvergunning. De officiële instanties beslissen; onze kennisbank noemt ze.",
  ],
  "detail.guideAll": ["Open the knowledge base", "Naar de kennisbank"],
  "detail.applyLogin": ["Log in as a student to apply", "Log in als student om te solliciteren"],
  "detail.applyStudentOnly": [
    "Only student accounts can apply to vacancies",
    "Alleen studentaccounts kunnen op vacatures solliciteren",
  ],
  "detail.applyTitle": ["Apply", "Solliciteren"],
  "detail.applyDesc": [
    "sees your name, university, CV link and motivation.",
    "ziet je naam, universiteit, cv-link en motivatie.",
  ],
  "detail.motivation": ["Why are you a good fit? *", "Waarom ben jij geschikt? *"],
  "detail.motivationPlaceholder": [
    "Tell the employer about your studies, availability and why this role fits you (min. 10 characters).",
    "Vertel de werkgever over je studie, beschikbaarheid en waarom deze functie bij je past (min. 10 tekens).",
  ],
  "detail.cvLabel": ["CV (optional)", "Cv (optioneel)"],
  "cv.upload": ["Upload CV", "Cv uploaden"],
  "cv.replace": ["Replace CV", "Cv vervangen"],
  "cv.remove": ["Remove", "Verwijderen"],
  "cv.view": ["View", "Bekijken"],
  "cv.none": ["No CV uploaded yet", "Nog geen cv geüpload"],
  "cv.hint": ["PDF, DOC or DOCX · max 5 MB", "PDF, DOC of DOCX · max 5 MB"],
  "cv.uploading": ["Uploading…", "Uploaden…"],
  "cv.uploaded": ["CV uploaded", "Cv geüpload"],
  "cv.removed": ["CV removed", "Cv verwijderd"],
  "cv.failed": ["Could not upload that file", "Kon dit bestand niet uploaden"],
  "cv.tooBig": ["That file is larger than 5 MB", "Dit bestand is groter dan 5 MB"],
  "cv.wrongType": ["Upload a PDF, DOC or DOCX file", "Upload een PDF-, DOC- of DOCX-bestand"],
  "cv.fromProfile": ["Using the CV from your profile", "Cv uit je profiel wordt gebruikt"],
  "cv.preview": ["Preview", "Voorbeeld"],
  "cv.hidePreview": ["Hide preview", "Voorbeeld verbergen"],
  "cv.openTab": ["Open in new tab", "Openen in nieuw tabblad"],
  "cv.previewHint": [
    "Scroll inside the preview to read the rest, or open it in a new tab to download.",
    "Scroll in het voorbeeld om verder te lezen, of open het in een nieuw tabblad om te downloaden.",
  ],
  "cv.previewUnsupported": [
    "This browser can't display PDFs inline.",
    "Deze browser kan PDF's niet direct weergeven.",
  ],
  "cv.applyHint": [
    "Upload a different CV for this application, or leave it to send the one on your profile.",
    "Upload een ander cv voor deze sollicitatie, of laat het staan om het cv uit je profiel te versturen.",
  ],
  "detail.send": ["Send application", "Sollicitatie versturen"],
  "detail.sending": ["Sending…", "Versturen…"],
  "detail.sent": [
    "Application sent — track it in your dashboard",
    "Sollicitatie verstuurd — volg hem in je dashboard",
  ],
  "detail.sendFailed": ["Could not send your application", "Kon je sollicitatie niet versturen"],
  "detail.seoFallbackTitle": ["Student vacancy", "Studentenvacature"],
  "detail.seoFallbackDescription": [
    "Student vacancy in the Netherlands on DutchVacancy.",
    "Studentenvacature in Nederland op DutchVacancy.",
  ],
  "detail.location": ["Location", "Locatie"],
  "detail.hours": ["Hours", "Uren"],
  "detail.schedule": ["Schedule", "Rooster"],
  "detail.contract": ["Contract", "Contractvorm"],
  "detail.start": ["Start date", "Startdatum"],
  "detail.published": ["Posted on", "Geplaatst op"],
  "detail.closes": ["Closes on", "Sluit op"],
  "detail.closedOn": ["Closed on", "Gesloten op"],
  "detail.closedTitle": ["This vacancy is closed", "Deze vacature is gesloten"],
  "detail.closedBody": [
    "It no longer accepts applications.",
    "Solliciteren is niet meer mogelijk.",
  ],
  "detail.closedBrowse": ["See open vacancies", "Bekijk open vacatures"],
  "detail.cvRequired": ["A CV is required to apply", "Een cv is verplicht bij het solliciteren"],
  "detail.cvRequiredHint": [
    "This employer asks for a CV with every application.",
    "Deze werkgever vraagt bij elke sollicitatie om een cv.",
  ],
  "detail.motivationMin": ["At least 10 characters", "Minimaal 10 tekens"],
  "detail.motivationOk": ["Ready to send", "Klaar om te versturen"],

  // ---------- auth ----------
  "login.title": ["Log in", "Inloggen"],
  "login.lead": [
    "Students and employers use the same login.",
    "Studenten en werkgevers gebruiken dezelfde login.",
  ],
  "login.email": ["Email", "E-mailadres"],
  "login.password": ["Password", "Wachtwoord"],
  "login.submit": ["Log in", "Inloggen"],
  "login.pending": ["Logging in…", "Inloggen…"],
  "login.failed": ["Login failed", "Inloggen mislukt"],
  "login.welcome": ["Welcome back", "Welkom terug"],
  "login.forgot": ["Forgot password?", "Wachtwoord vergeten?"],
  "login.demo": ["Demo accounts", "Demo-accounts"],
  "login.demoStudent": ["Student demo", "Studentdemo"],
  "login.demoEmployer": ["Employer demo", "Werkgeversdemo"],
  "login.noAccount": ["No account yet?", "Nog geen account?"],
  "login.createFree": ["Create one free", "Maak er gratis een aan"],
  "login.sideTitle": ["Welcome back to DutchVacancy", "Welkom terug bij DutchVacancy"],
  "login.sideBody": [
    "Search English-friendly jobs, manage applications and keep your profile in one place.",
    "Zoek Engelstalige vacatures, beheer sollicitaties en houd je profiel op één plek bij.",
  ],
  "login.quote": [
    "“I moved to Amsterdam without a word of Dutch. Two weeks later I had a 16-hour working-student contract in an English-speaking engineering team.”",
    "“Ik verhuisde naar Amsterdam zonder een woord Nederlands. Twee weken later had ik een werkstudentcontract van 16 uur in een Engelstalig engineeringteam.”",
  ],
  "login.quoteBy": ["— Aarav, MSc student, UvA", "— Aarav, masterstudent, UvA"],
  "register.title": ["Create your free account", "Maak je gratis account"],
  "register.roleStudent": ["I'm a student", "Ik ben student"],
  "register.roleEmployer": ["I'm an employer", "Ik ben werkgever"],
  "register.name": ["Full name", "Volledige naam"],
  "register.password": ["Password (min. 8 characters)", "Wachtwoord (min. 8 tekens)"],
  "register.company": ["Company name", "Bedrijfsnaam"],
  "register.companyCity": ["Company city", "Vestigingsplaats"],
  "register.submitStudent": ["Create student account", "Studentaccount aanmaken"],
  "register.submitEmployer": ["Create employer account", "Werkgeversaccount aanmaken"],
  "register.pending": ["Creating…", "Aanmaken…"],
  "register.created": ["Account created — welcome to DutchVacancy", "Account aangemaakt — welkom bij DutchVacancy"],
  "register.createdVerify": [
    "Account created. Check your inbox to verify your email.",
    "Account aangemaakt. Controleer je inbox om je e-mailadres te bevestigen.",
  ],
  "register.failed": ["Could not create your account", "Kon je account niet aanmaken"],
  "register.already": ["Already registered?", "Al geregistreerd?"],
  "register.sideTitle": [
    "What you get with a free account",
    "Wat je krijgt met een gratis account",
  ],
  "register.side1t": ["Language requirement up front", "Taaleis vooraf duidelijk"],
  "register.side1b": [
    "Every vacancy states whether English is enough.",
    "Bij elke vacature staat of Engels genoeg is.",
  ],
  "register.side2t": ["One profile for every application", "Eén profiel voor elke sollicitatie"],
  "register.side2b": [
    "Your profile and CV go with each application you send.",
    "Je profiel en cv gaan mee met elke sollicitatie die je verstuurt.",
  ],
  "register.side3t": ["Track your applications", "Volg je sollicitaties"],
  "register.side3b": [
    "Your dashboard shows when an employer reviews your application or invites you to an interview.",
    "Je dashboard laat zien wanneer een werkgever je sollicitatie bekijkt of je uitnodigt voor een gesprek.",
  ],
  "register.side4t": ["Free for students", "Gratis voor studenten"],
  "register.side4b": [
    "Creating an account and applying costs nothing.",
    "Een account maken en solliciteren kost niets.",
  ],

  // ---------- student dashboard ----------
  "sd.eyebrow": ["Student dashboard", "Studentdashboard"],
  "sd.hi": ["Hi", "Hoi"],
  "sd.statApplications": ["Applications", "Sollicitaties"],
  "sd.statSaved": ["Saved jobs", "Opgeslagen"],
  "sd.statInterviews": ["Interviews", "Gesprekken"],
  "sd.tabApplications": ["Applications", "Sollicitaties"],
  "sd.tabSaved": ["Saved jobs", "Opgeslagen vacatures"],
  "sd.tabProfile": ["Profile", "Profiel"],
  "sd.emptyAppsTitle": ["No applications yet", "Nog geen sollicitaties"],
  "sd.emptyAppsBody": [
    "Find an English-speaking role and apply in two clicks.",
    "Vind een Engelstalige functie en solliciteer in twee klikken.",
  ],
  "sd.browse": ["Browse jobs", "Vacatures bekijken"],
  "sd.emptySavedTitle": ["Nothing saved yet", "Nog niets opgeslagen"],
  "sd.emptySavedBody": [
    "Tap the bookmark on any vacancy to keep it here.",
    "Tik op de bladwijzer bij een vacature om hem hier te bewaren.",
  ],
  "sd.university": ["University", "Universiteit"],
  "sd.study": ["Study programme", "Studie"],
  "sd.city": ["Preferred city", "Voorkeursstad"],
  "sd.cityAny": ["All cities", "Alle steden"],
  "sd.englishLevel": ["English level", "Engels niveau"],
  "sd.phone": ["Phone", "Telefoon"],
  "sd.cv": ["CV", "Cv"],
  "sd.bio": ["Short introduction", "Korte introductie"],
  "sd.saveProfile": ["Save profile", "Profiel opslaan"],
  "sd.profileSaved": ["Profile updated", "Profiel bijgewerkt"],
  "sd.profileFailed": ["Could not save your profile", "Kon je profiel niet opslaan"],

  // ---------- employer dashboard ----------
  "ed.eyebrow": ["Employer dashboard", "Werkgeversdashboard"],
  "ed.company": ["Your company", "Jouw bedrijf"],
  "ed.post": ["Post a vacancy", "Vacature plaatsen"],
  "ed.statPublished": ["Published", "Gepubliceerd"],
  "ed.statDrafts": ["Drafts", "Concepten"],
  "ed.statApplicants": ["Applicants", "Kandidaten"],
  "ed.tabVacancies": ["Vacancies", "Vacatures"],
  "ed.tabApplicants": ["Applicants", "Kandidaten"],
  "ed.emptyVacTitle": ["No vacancies yet", "Nog geen vacatures"],
  "ed.emptyVacBody": [
    "Publish your first English-speaking student role.",
    "Plaats je eerste Engelstalige studentenfunctie.",
  ],
  "ed.draft": ["Draft", "Concept"],
  "ed.publish": ["Publish", "Publiceren"],
  "ed.unpublish": ["Unpublish", "Depubliceren"],
  "ed.published": ["Vacancy published", "Vacature gepubliceerd"],
  "ed.unpublished": ["Vacancy unpublished", "Vacature gedepubliceerd"],
  "ed.updateFailed": ["Could not update the vacancy", "Kon de vacature niet bijwerken"],
  "ed.deleted": ["Vacancy deleted", "Vacature verwijderd"],
  "ed.deleteFailed": ["Could not delete the vacancy", "Kon de vacature niet verwijderen"],
  "ed.statusUpdated": ["Applicant status updated", "Status kandidaat bijgewerkt"],
  "ed.statusFailed": ["Could not update the applicant", "Kon de kandidaat niet bijwerken"],
  "iv.title": ["Propose interview times", "Gespreksmomenten voorstellen"],
  "iv.desc": [
    "The candidate gets an email with a link to pick one of your times.",
    "De kandidaat ontvangt een e-mail met een link om een van jouw momenten te kiezen.",
  ],
  "iv.mode": ["Interview type", "Type gesprek"],
  "iv.online": ["Online", "Online"],
  "iv.onLocation": ["On location", "Op locatie"],
  "iv.locationOnline": ["Meeting link", "Vergaderlink"],
  "iv.locationOn": ["Address", "Adres"],
  "iv.note": ["Note for the candidate (optional)", "Bericht voor de kandidaat (optioneel)"],
  "iv.slots": ["Proposed times (max. 5)", "Voorgestelde momenten (max. 5)"],
  "iv.addSlot": ["Add a time", "Moment toevoegen"],
  "iv.removeSlot": ["Remove this time", "Dit moment verwijderen"],
  "iv.send": ["Send invitation", "Uitnodiging versturen"],
  "iv.sending": ["Sending…", "Versturen…"],
  "iv.sent": ["Invitation sent", "Uitnodiging verstuurd"],
  "iv.failed": ["Could not send the invitation", "Kon de uitnodiging niet versturen"],
  "iv.propose": ["Propose times", "Momenten voorstellen"],
  "iv.reschedule": ["Propose new times", "Nieuwe momenten voorstellen"],
  "iv.awaiting": ["Waiting for the candidate to choose a time", "Wacht tot de kandidaat een moment kiest"],
  "iv.scheduled": ["Interview scheduled", "Gesprek gepland"],
  "iv.where": ["Where", "Waar"],
  "iv.pick": ["Choose a time", "Kies een moment"],
  "iv.pageTitle": ["Choose your interview time", "Kies je gesprekstijd"],
  "iv.pageIntro": [
    "Select the time that suits you best. Times are shown in your own time zone.",
    "Kies het moment dat jou het beste past. Tijden worden in jouw eigen tijdzone getoond.",
  ],
  "iv.confirm": ["Confirm this time", "Bevestig dit moment"],
  "iv.confirming": ["Confirming…", "Bevestigen…"],
  "iv.confirmed": ["Your interview is scheduled", "Je gesprek staat gepland"],
  "iv.chooseFailed": ["Could not save your choice", "Kon je keuze niet opslaan"],
  "iv.none": [
    "There is no interview waiting for a time for this application.",
    "Er wacht geen gesprek op een tijdstip bij deze sollicitatie.",
  ],
  "iv.back": ["Back to dashboard", "Terug naar dashboard"],
  "iv.addToCalendar": ["Add to calendar", "Toevoegen aan agenda"],
  "ed.fresh": ["Fresh. €14.95 excl. VAT", "Fresh. €14,95 excl. btw"],
  "ed.freshActive": ["Fresh active", "Fresh actief"],
  "ed.freshFailed": ["Could not start Fresh Vacancy checkout", "Kon de Fresh Vacancy-betaling niet starten"],
  "ed.extendHint": [
    "edit the vacancy and set a new closing date to reopen it",
    "pas de vacature aan en kies een nieuwe sluitingsdatum om hem te heropenen",
  ],
  "ed.filterAll": ["All", "Alle"],
  "ed.emptyAppsTitle": ["No applicants in this view", "Geen kandidaten in deze weergave"],
  "ed.emptyAppsBody": [
    "Applications appear here as students apply.",
    "Sollicitaties verschijnen hier zodra studenten solliciteren.",
  ],
  "ed.openCv": ["Open CV", "Cv openen"],
  "ed.editAria": ["Edit vacancy", "Vacature bewerken"],
  "ed.deleteAria": ["Delete vacancy", "Vacature verwijderen"],

  // ---------- vacancy form ----------
  "vf.editTitle": ["Edit vacancy", "Vacature bewerken"],
  "vf.newTitle": ["Post a new vacancy", "Nieuwe vacature plaatsen"],
  "vf.lead": [
    "Be explicit about the English requirement and permit support — it's why students trust this board.",
    "Wees duidelijk over de Engelse taaleis en de vergunningshulp — daarom vertrouwen studenten deze vacaturebank.",
  ],
  "vf.title": ["Job title *", "Functietitel *"],
  "vf.city": ["City", "Stad"],
  "vf.category": ["Category", "Categorie"],
  "vf.jobType": ["Job type", "Soort baan"],
  "vf.english": ["English requirement", "Engelse taaleis"],
  "vf.permit": ["Work permit (TWV)", "Werkvergunning (TWV)"],
  "vf.workMode": ["Work arrangement", "Werkvorm"],
  "vf.hours": ["Hours per week", "Uren per week"],
  "vf.rateFrom": ["From (€)", "Vanaf (€)"],
  "vf.rateTo": ["Up to (€)", "Tot (€)"],
  "vf.description": ["Description", "Beschrijving"],
  "vf.requirements": ["Requirements (one per line)", "Vereisten (één per regel)"],
  "vf.perks": ["Perks (one per line)", "Extra's (één per regel)"],
  "vf.publishNow": [
    "Publish immediately (uncheck to keep as draft)",
    "Direct publiceren (vink uit om als concept te bewaren)",
  ],
  "vf.create": ["Create vacancy", "Vacature aanmaken"],
  "vf.saveChanges": ["Save changes", "Wijzigingen opslaan"],
  "vf.created": ["Vacancy created", "Vacature aangemaakt"],
  "vf.updated": ["Vacancy updated", "Vacature bijgewerkt"],
  "vf.failed": ["Could not save the vacancy", "Kon de vacature niet opslaan"],
  "vf.optional": ["optional", "optioneel"],
  "vf.notStated": ["Not stated", "Niet opgegeven"],
  "vf.contract": ["Contract form", "Contractvorm"],
  "vf.pay": ["Pay (gross)", "Salaris (bruto)"],
  "vf.payHint": [
    "Leave empty if you prefer not to state pay — nothing is filled in for you.",
    "Laat leeg als je geen salaris wilt vermelden — er wordt dan niets voor je ingevuld.",
  ],
  "vf.payPeriod": ["Per", "Per"],
  "vf.perHour": ["hour", "uur"],
  "vf.perMonth": ["month", "maand"],
  "vf.schedule": ["Schedule", "Rooster"],
  "vf.schedulePlaceholder": ["e.g. Wednesday and Friday evenings, Saturdays", "bijv. woensdag- en vrijdagavond, zaterdag"],
  "vf.scheduleTags": ["Type of hours", "Soort uren"],
  "vf.start": ["Start date", "Startdatum"],
  "vf.closes": ["Closing date", "Sluitingsdatum"],
  "vf.closesHint": [
    "Required to publish. After this date the vacancy is closed automatically; you can extend it.",
    "Verplicht om te publiceren. Na deze datum sluit de vacature automatisch; je kunt hem verlengen.",
  ],
  "vf.cvRequired": ["Require a CV with every application", "Cv verplicht bij elke sollicitatie"],
  "err.email_not_verified": [
    "Confirm your email address first — use the link we sent you, or request a new one at the top of the page.",
    "Bevestig eerst je e-mailadres via de link die we je stuurden, of vraag bovenaan de pagina een nieuwe aan.",
  ],
  "err.job_not_found": ["This vacancy no longer exists.", "Deze vacature bestaat niet meer."],
  "err.job_closed": ["This vacancy is closed and no longer accepts applications.", "Deze vacature is gesloten; solliciteren is niet meer mogelijk."],
  "err.already_applied": ["You already applied to this vacancy.", "Je hebt al op deze vacature gesolliciteerd."],
  "err.cv_required": ["Please add your CV — this employer requires one.", "Voeg je cv toe — deze werkgever vraagt erom."],
  "err.closing_date_required": ["Set a closing date before publishing.", "Kies een sluitingsdatum voordat je publiceert."],
  "err.closing_date_past": ["The closing date must be in the future to publish.", "De sluitingsdatum moet in de toekomst liggen om te publiceren."],
  "err.closing_date_too_far": ["The closing date can be at most 180 days ahead.", "De sluitingsdatum mag maximaal 180 dagen vooruit liggen."],

  // ---------- 404 ----------
  "nf.title": ["Page not found", "Pagina niet gevonden"],
  "nf.body": [
    "That page doesn't exist. Try the job board instead.",
    "Deze pagina bestaat niet. Bekijk in plaats daarvan de vacaturebank.",
  ],

  // ---------- about ----------
  "about.eyebrow": ["About us", "Over ons"],
  "about.title": [
    "English-friendly jobs, without the guesswork",
    "Engelstalige vacatures, zonder giswerk",
  ],
  "about.intro": [
    "DutchVacancy helps international students and English-speaking candidates find roles in the Netherlands with clear requirements.",
    "DutchVacancy helpt internationale studenten en Engelstalige kandidaten functies in Nederland te vinden met duidelijke vereisten.",
  ],
  "about.s1t": ["Why we exist", "Waarom wij bestaan"],
  "about.s1b": [
    [
      "Finding work in the Netherlands can be unnecessarily unclear when a vacancy does not state its working language, hours or permit support.",
      "Every vacancy on DutchVacancy states its language requirement and closing date. Hours, pay (per hour or per month), contract type and start date are shown whenever the employer provides them — we never fill them in ourselves.",
    ],
    [
      "Werk vinden in Nederland is onnodig onduidelijk wanneer een vacature niets zegt over de werktaal, uren of vergunningshulp.",
      "Bij elke vacature op DutchVacancy staan de taaleis en de sluitingsdatum. Uren, loon (per uur of per maand), contractvorm en startdatum tonen we zodra de werkgever ze opgeeft — we vullen ze nooit zelf in.",
    ],
  ],
  "about.s2t": ["What we do for employers", "Wat wij voor werkgevers doen"],
  "about.s2b": [
    [
      "Employers can publish the information international candidates need and manage applications from one dashboard.",
    ],
    [
      "Werkgevers kunnen de informatie publiceren die internationale kandidaten nodig hebben en sollicitaties vanuit één dashboard beheren.",
    ],
  ],
  "about.s3t": ["What we are not", "Wat wij niet zijn"],
  "about.s3b": [
    [
      "We are not a recruitment agency and we never charge students. We are not affiliated with the IND, UWV or any Dutch government body. Our knowledge base explains the rules and names its official sources; the official bodies decide in your situation.",
    ],
    [
      "Wij zijn geen uitzendbureau en studenten betalen nooit. Wij zijn niet verbonden aan de IND, het UWV of een andere Nederlandse overheidsinstantie. Onze kennisbank legt de regels uit en noemt de officiële bronnen; de officiële instanties beslissen over jouw situatie.",
    ],
  ],

  // ---------- how it works ----------
  "how.eyebrow": ["How it works", "Hoe het werkt"],
  "how.title": [
    "From signing up to your first Dutch payslip",
    "Van aanmelden tot je eerste Nederlandse loonstrook",
  ],
  "how.intro": [
    "The same platform serves two audiences. Here is exactly what happens on each side.",
    "Hetzelfde platform dient twee doelgroepen. Dit gebeurt er aan beide kanten.",
  ],
  "how.studentsTitle": ["For international students", "Voor internationale studenten"],
  "how.studentSteps": [
    [
      "Create a free student account. Name, email and a password — that's it.",
      "Complete your profile. University, study programme, city, English level and your CV. It is reused on every application.",
      "Filter honestly. Pick “English only” and, if you are from outside the EU/EEA, “Employer applies for a TWV”.",
      "Apply with a motivation note. The employer sees your name, university, CV and your note.",
      "Track the outcome. Applied → under review → interview → offer, all in your dashboard.",
    ],
    [
      "Maak een gratis studentaccount. Naam, e-mailadres en wachtwoord — dat is alles.",
      "Vul je profiel in. Universiteit, studie, stad, Engels niveau en je cv. Dit wordt bij elke sollicitatie hergebruikt.",
      "Filter eerlijk. Kies “Alleen Engels” en, als je van buiten de EU/EER komt, “Werkgever vraagt TWV aan”.",
      "Solliciteer met een motivatie. De werkgever ziet je naam, universiteit, cv en je motivatie.",
      "Volg het resultaat. Gesolliciteerd → in behandeling → gesprek → aanbod, allemaal in je dashboard.",
    ],
  ],
  "how.employersTitle": ["For Dutch employers", "Voor Nederlandse werkgevers"],
  "how.employerSteps": [
    [
      "Register an employer account with your company name and city.",
      "Publish a vacancy — title, city, job type, language requirement and closing date, plus hours, pay and contract type if you want to state them.",
      "Keep drafts private. Uncheck “publish” while you're still writing; nothing is visible until you're ready.",
      "Review applicants in one pipeline, open CVs, and move candidates through the stages.",
      "Edit or unpublish anytime. A filled role should stop attracting applications.",
    ],
    [
      "Registreer een werkgeversaccount met je bedrijfsnaam en vestigingsplaats.",
      "Plaats een vacature — titel, stad, soort baan, taaleis en sluitingsdatum, plus uren, loon en contractvorm als je die wilt vermelden.",
      "Houd concepten privé. Vink “publiceren” uit terwijl je nog schrijft; niets is zichtbaar tot jij klaar bent.",
      "Beoordeel kandidaten in één overzicht, open cv's en zet kandidaten door naar de volgende fase.",
      "Bewerk of depubliceer wanneer je wilt. Een gevulde functie hoeft geen sollicitaties meer te trekken.",
    ],
  ],
  "how.costTitle": ["What it costs", "Wat het kost"],
  "how.costBody": [
    [
      "Free for students, always. Employer listings are free during our launch period in the Netherlands.",
    ],
    [
      "Altijd gratis voor studenten. Vacatures van werkgevers zijn gratis tijdens onze introductieperiode in Nederland.",
    ],
  ],

  // ---------- knowledge base (/guide) ----------
  "guide.eyebrow": ["Knowledge base", "Kennisbank"],
  "guide.title": [
    "Working in the Netherlands as an international student",
    "Werken als internationale student in Nederland",
  ],
  "guide.intro": [
    "Plain explanations of the rules for working alongside your studies. Every article names its official sources and when they were last read.",
    "Duidelijke uitleg over de regels voor werken naast je studie. Elk artikel noemt zijn officiële bronnen en wanneer die voor het laatst zijn gelezen.",
  ],
  "kb.articles": ["Articles", "Artikelen"],
  "kb.none": [
    "Our articles are checked by our content reviewer before we publish them. Until then, the official bodies below have the answers.",
    "Onze artikelen worden eerst door onze inhoudelijk eigenaar gecontroleerd voordat we ze publiceren. Tot die tijd vind je de antwoorden bij de officiële instanties hieronder.",
  ],
  "kb.official": ["Official bodies", "Officiële instanties"],
  "kb.official.ind": ["Residence permits, including for study", "Verblijfsvergunningen, ook voor studie"],
  "kb.official.uwv": ["Work permits (TWV) — your employer applies", "Werkvergunningen (TWV) — je werkgever vraagt aan"],
  "kb.official.svb": ["Whether you are insured in the Netherlands", "Of je in Nederland verzekerd bent"],
  "kb.official.rvo": ["Minimum wage, contracts and payslips", "Minimumloon, contracten en loonstroken"],
  "kb.official.bd": ["Taxes and the payroll tax credit", "Belasting en loonheffingskorting"],
  "kb.findWork": ["Find work", "Werk vinden"],
  "kb.findWorkBody": [
    "Vacancies where, according to the employer, English is enough.",
    "Vacatures waarvoor volgens de werkgever Engels genoeg is.",
  ],
  "kb.findWorkCta": ["See English-only vacancies", "Bekijk vacatures met alleen Engels"],
  "kb.employers": ["For employers", "Voor werkgevers"],
  "kb.employersBody": [
    "Hiring an international student? See how publishing a vacancy and handling applications works.",
    "Een internationale student aannemen? Lees hoe je een vacature plaatst en sollicitaties afhandelt.",
  ],
  "kb.employersCta": ["Information for employers", "Informatie voor werkgevers"],
  "kb.draft": ["Draft — not reviewed", "Concept — niet beoordeeld"],
  "kb.draftBanner": [
    "Draft for internal review. Not yet checked by our content reviewer and not shown on the live site.",
    "Concept voor interne controle. Nog niet gecontroleerd door onze inhoudelijk eigenaar en niet zichtbaar op de live site.",
  ],
  "kb.answer": ["Short answer", "Kort antwoord"],
  "kb.appliesTo": ["Who this applies to", "Voor wie geldt dit?"],
  "kb.exceptions": ["Exceptions", "Uitzonderingen"],
  "kb.nextSteps": ["What you can do now", "Wat kun je nu doen?"],
  "kb.contacts": ["Where to arrange it", "Waar regel je dit?"],
  "kb.decides": [
    "The official body decides in your situation. In doubt? Ask them.",
    "De officiële instantie beslist over jouw situatie. Twijfel je? Vraag het na.",
  ],
  "kb.related": ["Read next", "Lees ook"],
  "kb.sources": ["Official sources", "Officiële bronnen"],
  "kb.readOn": ["read on", "gelezen op"],
  "kb.inDutch": ["in Dutch", "Nederlandstalig"],
  "kb.author": ["Editor", "Redactie"],
  "kb.reviewer": ["Reviewed by", "Beoordeeld door"],
  "kb.lastReviewed": ["Last checked", "Laatst gecontroleerd"],
  "kb.notReviewed": ["Not yet reviewed by a person", "Nog niet door een persoon beoordeeld"],
  "kb.noAuthor": ["No author assigned yet", "Nog geen auteur toegewezen"],
  "kb.back": ["All articles", "Alle artikelen"],
  "kb.loadFailed": ["Could not load this article.", "Dit artikel kon niet worden geladen."],

  // ---------- employers (/employers) ----------
  // Only what the platform actually does today — no customer numbers, logos or results.
  "emp.eyebrow": ["For employers", "Voor werkgevers"],
  "emp.title": [
    "Hire international students who work in English",
    "Neem internationale studenten aan die in het Engels werken",
  ],
  "emp.intro": [
    "Publish a vacancy with a clear language requirement and handle applications, interviews and closing dates in one place.",
    "Plaats een vacature met een duidelijke taaleis en regel sollicitaties, gesprekken en sluitingsdata op één plek.",
  ],
  "emp.howTitle": ["How it works", "Zo werkt het"],
  "emp.steps": [
    [
      "Create a free employer account with your company name.",
      "Publish a vacancy: title, city, language requirement and closing date, plus hours, pay and contract type if you want to state them. Drafts stay private.",
      "Applications arrive in your dashboard with the candidate's profile, CV and motivation, and by email.",
      "Invite a candidate by proposing up to five interview times, online or on location. The candidate picks one and you both get a calendar invite.",
      "On the closing date the vacancy closes by itself and disappears from the listings. You can extend it before then.",
    ],
    [
      "Maak een gratis werkgeversaccount aan met je bedrijfsnaam.",
      "Plaats een vacature: titel, stad, taaleis en sluitingsdatum, plus uren, loon en contractvorm als je die wilt vermelden. Concepten blijven privé.",
      "Sollicitaties komen binnen in je dashboard, met het profiel, het cv en de motivatie van de kandidaat, en per e-mail.",
      "Nodig een kandidaat uit door maximaal vijf gesprekstijden voor te stellen, online of op locatie. De kandidaat kiest er één en jullie krijgen allebei een agenda-uitnodiging.",
      "Op de sluitingsdatum sluit de vacature vanzelf en verdwijnt ze uit het overzicht. Je kunt haar daarvoor verlengen.",
    ],
  ],
  "emp.studentsTitle": ["What students see", "Wat studenten zien"],
  "emp.studentsBody": [
    "Every vacancy shows its language requirement and closing date, and the hours, pay, contract type and start date you provided. Students filter on these, so being specific brings better-matched applications.",
    "Elke vacature toont de taaleis en de sluitingsdatum, en de uren, het loon, de contractvorm en de startdatum die je opgaf. Studenten filteren hierop, dus concreet zijn levert beter passende sollicitaties op.",
  ],
  "emp.permitTitle": ["Hiring a student from outside the EU/EEA", "Een student van buiten de EU/EER aannemen"],
  "emp.permitBody": [
    "Check before the first working day whether a work permit (TWV) is needed and apply for it in time. Our knowledge base explains when it is needed; UWV handles the application.",
    "Controleer vóór de eerste werkdag of een werkvergunning (TWV) nodig is en vraag die op tijd aan. Onze kennisbank legt uit wanneer die nodig is; UWV behandelt de aanvraag.",
  ],
  "emp.permitArticle": ["When is a TWV needed?", "Wanneer is een TWV nodig?"],
  "emp.permitUwv": ["UWV: work permit for a working student", "UWV: werkvergunning werkstudent"],
  "emp.startCta": ["Create an employer account", "Maak een werkgeversaccount"],
  "emp.formTitle": ["Questions first? Send us your request", "Eerst vragen? Stuur ons je aanvraag"],
  "emp.formIntro": [
    "Tell us which roles you are hiring for. We use your details only to reply to this request.",
    "Vertel ons voor welke functies je zoekt. We gebruiken je gegevens alleen om op deze aanvraag te reageren.",
  ],
  "emp.company": ["Company", "Bedrijf"],
  "emp.message": ["Which roles, where and from when?", "Welke functies, waar en vanaf wanneer?"],
  "emp.send": ["Send request", "Aanvraag versturen"],
  "emp.subject": ["Employer request", "Werkgeversaanvraag"],
  "emp.sent": [
    "Thanks — your request has been received. We will reply by email.",
    "Bedankt — je aanvraag is ontvangen. We reageren per e-mail.",
  ],
  "emp.sentDays": [
    "Thanks — your request has been received. We will reply by email within {n} working days.",
    "Bedankt — je aanvraag is ontvangen. We reageren binnen {n} werkdagen per e-mail.",
  ],

  // ---------- contact ----------
  "contact.eyebrow": ["Contact", "Contact"],
  "contact.title": ["Talk to the DutchVacancy team", "Praat met het DutchVacancy-team"],
  "contact.intro": [
    "Questions about a vacancy, your account, or hiring international students? Send us a message.",
    "Vragen over een vacature, je account of het aannemen van internationale studenten? Stuur ons een bericht.",
  ],
  "contact.name": ["Your name", "Je naam"],
  "contact.email": ["Email", "E-mailadres"],
  "contact.subject": ["Subject", "Onderwerp"],
  "contact.message": ["Message", "Bericht"],
  "contact.send": ["Send message", "Bericht versturen"],
  "contact.sending": ["Sending…", "Versturen…"],
  "contact.sent": ["Thanks — your message has been received.", "Bedankt — je bericht is ontvangen."],
  "contact.failed": ["Could not send your message", "Kon je bericht niet versturen"],
  "contact.emailLabel": ["Email", "E-mail"],
  "contact.office": ["Office", "Kantoor"],
  "contact.answerNote": ["We answer in English and Dutch.", "We antwoorden in het Engels en Nederlands."],
  // {n} = RESPONSE_WORKING_DAYS in config/operations.ts, only once confirmed achievable.
  "contact.answerNoteDays": [
    "We answer in English and Dutch, within {n} working days.",
    "We antwoorden in het Engels en Nederlands, binnen {n} werkdagen.",
  ],

  // ---------- privacy ----------
  "privacy.eyebrow": ["Privacy policy", "Privacybeleid"],
  "privacy.title": ["How DutchVacancy handles your data", "Hoe DutchVacancy met je gegevens omgaat"],
  "privacy.intro": [
    "Last updated: 29 September 2026. We process personal data under the EU GDPR and Dutch implementation act (UAVG).",
    "Laatst bijgewerkt: 29 september 2026. Wij verwerken persoonsgegevens volgens de AVG en de Nederlandse Uitvoeringswet (UAVG).",
  ],
  "privacy.s1t": ["What we collect", "Wat wij verzamelen"],
  "privacy.s1b": [
    [
      "Students: name, email address, password (hashed), university, study programme, city, English level, phone number, the CV file you upload, introduction text, saved jobs and applications.",
      "Employers: name, email address, password (hashed), company name, city, industry, website, the vacancies you publish and the interview times you propose.",
      "Everyone: a session cookie that keeps you logged in, and any message or employer request you send through our forms (name, email address, company, message).",
    ],
    [
      "Studenten: naam, e-mailadres, wachtwoord (gehasht), universiteit, studie, stad, Engels niveau, telefoonnummer, het cv-bestand dat je uploadt, introductietekst, opgeslagen vacatures en sollicitaties.",
      "Werkgevers: naam, e-mailadres, wachtwoord (gehasht), bedrijfsnaam, plaats, branche, website, de vacatures die je plaatst en de gesprekstijden die je voorstelt.",
      "Iedereen: een sessiecookie waarmee je ingelogd blijft, en elk bericht of elke werkgeversaanvraag die je via onze formulieren verstuurt (naam, e-mailadres, bedrijf, bericht).",
    ],
  ],
  "privacy.s2t": ["Why we process it", "Waarom wij dit verwerken"],
  "privacy.s2b": [
    [
      "To operate your account, show you relevant vacancies, deliver your applications to the employer you chose, and answer your support messages. When you apply to a vacancy, the employer receives your name, email, university, CV and motivation text — that is the purpose of applying.",
    ],
    [
      "Om je account te laten werken, relevante vacatures te tonen, je sollicitaties te bezorgen bij de werkgever die jij koos en je vragen te beantwoorden. Als je op een vacature solliciteert, ontvangt de werkgever je naam, e-mailadres, universiteit, cv en motivatie — dat is het doel van solliciteren.",
    ],
  ],
  "privacy.s3t": ["Cookies", "Cookies"],
  "privacy.s3b": [
    [
      "We set one strictly necessary, httpOnly session cookie. Your language choice is stored in your own browser (local storage), not sent to us. We do not use advertising or cross-site tracking cookies, and our visitor statistics use no cookies at all.",
    ],
    [
      "Wij plaatsen één strikt noodzakelijke httpOnly-sessiecookie. Je taalkeuze wordt in je eigen browser bewaard (local storage) en niet naar ons gestuurd. Wij gebruiken geen advertentie- of trackingcookies, en onze bezoekersstatistieken gebruiken helemaal geen cookies.",
    ],
  ],
  "privacy.s4t": ["Retention", "Bewaartermijn"],
  "privacy.s4b": [
    [
      "Account and application data is kept while your account exists. You can delete your account or request deletion at any time. Employers may need to retain limited records where Dutch law requires it.",
    ],
    [
      "Account- en sollicitatiegegevens bewaren wij zolang je account bestaat. Je kunt je account verwijderen of altijd om verwijdering vragen. Werkgevers moeten mogelijk beperkte gegevens bewaren als de Nederlandse wet dat vereist.",
    ],
  ],
  "privacy.s5t": ["Your rights", "Jouw rechten"],
  "privacy.s5b": [
    [
      "You have the right to access, correct, export, restrict or delete your data, and to object to processing. Contact us through the contact form and we will respond within one month. You may also complain to the Autoriteit Persoonsgegevens, the Dutch data protection authority.",
    ],
    [
      "Je hebt het recht je gegevens in te zien, te corrigeren, te exporteren, te beperken of te laten verwijderen, en om bezwaar te maken tegen de verwerking. Neem contact op via het contactformulier en wij reageren binnen een maand. Je kunt ook een klacht indienen bij de Autoriteit Persoonsgegevens.",
    ],
  ],

  "privacy.s6t": ["Services we use", "Diensten die wij gebruiken"],
  "privacy.s6b": [
    [
      "Hosting: the site and its database run on a server we rent from TransIP.",
      "Email: account, application and interview emails are sent through Resend. When a student applies, we also send ourselves a short follow-up record (application number, vacancy, company and whether the notifications went out) — never the candidate's details, motivation or CV.",
      "Error monitoring: when something breaks, a technical error report goes to Sentry. We configured it not to send request contents, form data or IP addresses.",
      "Visitor statistics: on dutchvacancy.nl we count visits and a few actions (for example 'application sent') with Plausible Analytics, without cookies and without personal data. We never send names, email addresses, CV or form contents to it.",
      "Payments: if an employer buys a paid option, Stripe collects the payment details directly during checkout. We never see or store card numbers — only the confirmation that the payment succeeded.",
      "We do not sell your data and do not share it with advertisers or data brokers.",
    ],
    [
      "Hosting: de site en de database draaien op een server die wij huren bij TransIP.",
      "E-mail: e-mails over je account, sollicitaties en gesprekken versturen wij via Resend. Als een student solliciteert, sturen wij onszelf ook een kort opvolgbericht (sollicitatienummer, vacature, bedrijf en of de meldingen zijn verstuurd) — nooit de gegevens van de kandidaat, de motivatie of het cv.",
      "Foutmeldingen: als er iets misgaat, gaat een technisch foutrapport naar Sentry. Wij hebben dit zo ingesteld dat er geen verzoekinhoud, formuliergegevens of IP-adressen worden meegestuurd.",
      "Bezoekersstatistieken: op dutchvacancy.nl tellen wij bezoeken en enkele handelingen (bijvoorbeeld 'sollicitatie verstuurd') met Plausible Analytics, zonder cookies en zonder persoonsgegevens. Namen, e-mailadressen, cv's of formulierinhoud sturen wij daar nooit naartoe.",
      "Betalingen: als een werkgever een betaalde optie koopt, verzamelt Stripe de betaalgegevens rechtstreeks tijdens het afrekenen. Wij zien of bewaren nooit kaartnummers — alleen de bevestiging dat de betaling is gelukt.",
      "Wij verkopen je gegevens niet en delen ze niet met adverteerders of databrokers.",
    ],
  ],

  // ---------- terms ----------
  "terms.eyebrow": ["Terms of service", "Algemene voorwaarden"],
  "terms.title": ["The rules for using DutchVacancy", "De regels voor het gebruik van DutchVacancy"],
  "terms.intro": [
    "Last updated: 1 January 2026. By creating an account you agree to these terms.",
    "Laatst bijgewerkt: 1 januari 2026. Door een account aan te maken ga je akkoord met deze voorwaarden.",
  ],
  "terms.s1t": ["Using the platform", "Gebruik van het platform"],
  "terms.s1b": [
    [
      "You need an account to apply to vacancies or publish them. Keep your login details to yourself, give accurate information, and use one account per person or company.",
    ],
    [
      "Je hebt een account nodig om op vacatures te solliciteren of ze te plaatsen. Houd je inloggegevens voor jezelf, geef juiste informatie en gebruik één account per persoon of bedrijf.",
    ],
  ],
  "terms.s2t": ["Student obligations", "Verplichtingen van studenten"],
  "terms.s2b": [
    [
      "You are responsible for checking that a role fits your residence permit and your permitted working hours. Apply only to roles you genuinely intend to take, and never misrepresent your studies, permit status or work experience.",
    ],
    [
      "Je bent zelf verantwoordelijk om te controleren of een functie past bij je verblijfsvergunning en je toegestane werkuren. Solliciteer alleen op functies die je echt wilt, en geef nooit een onjuist beeld van je studie, vergunningstatus of werkervaring.",
    ],
  ],
  "terms.s3t": ["Employer obligations", "Verplichtingen van werkgevers"],
  "terms.s3b": [
    [
      "Vacancies must be real, must state the English requirement, hours and hourly rate accurately, and must comply with Dutch employment law — including minimum wage, holiday allowance and equal-treatment rules. You may not charge students any fee, and you may not use applicant data for anything other than the role they applied to.",
    ],
    [
      "Vacatures moeten echt zijn, de Engelse taaleis, uren en het uurloon correct vermelden en voldoen aan het Nederlandse arbeidsrecht — inclusief minimumloon, vakantiegeld en gelijke behandeling. Je mag studenten geen kosten in rekening brengen en kandidaatgegevens alleen gebruiken voor de functie waarop is gesolliciteerd.",
    ],
  ],
  "terms.s4t": ["Content we remove", "Content die wij verwijderen"],
  "terms.s4b": [
    [
      "We remove listings that are discriminatory, misleading, unpaid where pay is legally required, pyramid-style, or that require the candidate to pay for a permit, training or equipment.",
    ],
    [
      "Wij verwijderen vacatures die discriminerend of misleidend zijn, onbetaald terwijl loon wettelijk verplicht is, piramidespelen, of waarbij de kandidaat moet betalen voor een vergunning, training of materiaal.",
    ],
  ],
  "terms.s5t": ["No employment guarantee", "Geen garantie op werk"],
  "terms.s5b": [
    [
      "DutchVacancy is a marketplace, not an employer or agency. We do not guarantee that a vacancy leads to an offer, nor that an applicant is suitable, and we are not a party to any employment contract you enter into.",
    ],
    [
      "DutchVacancy is een platform, geen werkgever of uitzendbureau. Wij garanderen niet dat een vacature tot een aanbod leidt, noch dat een kandidaat geschikt is, en wij zijn geen partij bij een arbeidsovereenkomst die je sluit.",
    ],
  ],
  "terms.s6t": ["Liability and law", "Aansprakelijkheid en recht"],
  "terms.s6b": [
    [
      "The service is provided “as is”. To the extent permitted by law, our liability is limited to direct damage up to € 250. These terms are governed by Dutch law, with the courts of Amsterdam having jurisdiction.",
    ],
    [
      "De dienst wordt geleverd “zoals hij is”. Voor zover de wet dit toestaat, is onze aansprakelijkheid beperkt tot directe schade tot € 250. Op deze voorwaarden is Nederlands recht van toepassing; de rechtbank Amsterdam is bevoegd.",
    ],
  ],
  "terms.s7t": ["Fresh Vacancy (paid promotion)", "Fresh Vacancy (betaalde promotie)"],
  "terms.s7b": [
    [
      "Employers can promote one published vacancy as “Fresh Vacancy” for € 14.95 excluding VAT. For 24 hours it is shown in one of the three featured places on the home page, labelled as sponsored. At most 3 vacancies can be Fresh at the same time, platform-wide; if all places are taken at the moment of payment, the vacancy is not promoted and the payment is refunded.",
      "Payment is processed by Stripe at the moment of purchase. Once a placement has started, the fee is not refundable, including if you unpublish or close the vacancy early. We may change the price, duration or availability of this feature; the terms shown at checkout apply to that purchase.",
    ],
    [
      "Werkgevers kunnen één gepubliceerde vacature promoten als “Fresh Vacancy” voor € 14,95 excl. btw. De vacature staat dan 24 uur op een van de drie uitgelichte plekken op de homepage, met het label gesponsord. Er kunnen platformbreed maximaal 3 vacatures tegelijk Fresh zijn; zijn alle plekken bezet op het moment van betalen, dan wordt de vacature niet gepromoot en wordt de betaling terugbetaald.",
      "Betaling wordt verwerkt door Stripe op het moment van aankoop. Zodra een plaatsing is gestart, wordt het bedrag niet terugbetaald, ook niet als je de vacature eerder depubliceert of sluit. Wij kunnen de prijs, duur of beschikbaarheid van deze functie wijzigen; de voorwaarden die bij het afrekenen worden getoond, gelden voor die aankoop.",
    ],
  ],
};
